# Generated by Django 2.2.3 on 2019-08-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroperatelog',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bg_telephone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
    ]
