# Generated by Django 2.2.3 on 2019-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190820_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isadmin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('2', '监察员'), ('1', '管理员'), ('0', '普通用户')], default='0', max_length=1, verbose_name='用户角色'),
        ),
    ]
