# Generated by Django 2.2.3 on 2019-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190829_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperatelog',
            name='content_id',
            field=models.IntegerField(default=2, verbose_name='文件编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useroperatelog',
            name='content',
            field=models.CharField(max_length=50, verbose_name='文件名称'),
        ),
    ]
