# Generated by Django 2.2.3 on 2019-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190829_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperatelog',
            name='userno',
            field=models.CharField(default='111111', max_length=15, verbose_name='工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroperatelog',
            name='comment',
            field=models.CharField(default='1111', max_length=20, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userno',
            field=models.CharField(default='1111', max_length=15, verbose_name='工号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useroperatelog',
            name='username',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('3', '监察员'), ('2', '管理员'), ('1', '普通用户'), ('0', '离职员工')], default='1', max_length=1, verbose_name='用户角色'),
        ),
    ]
