# Generated by Django 2.2.3 on 2019-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191025_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.IntegerField(default=0, verbose_name='超级管理员'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('3', '监察稽核员'), ('2', '系统管理员'), ('1', '普通员工'), ('0', '离职员工')], default='1', max_length=1, verbose_name='用户角色'),
        ),
    ]
