# Generated by Django 2.2.3 on 2019-11-06 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191106_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='modify_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
