# Generated by Django 2.2.3 on 2019-08-15 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名称')),
                ('filepath', models.CharField(max_length=200, verbose_name='文件路径')),
                ('owner', models.CharField(max_length=200, verbose_name='文件所属用户')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '上传文件列表',
                'verbose_name_plural': '上传文件列表',
            },
        ),
    ]
