# Generated by Django 2.2.3 on 2019-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=300, verbose_name='指定的ip地址')),
            ],
            options={
                'verbose_name': '指定的ip地址',
                'verbose_name_plural': '指定的ip地址',
            },
        ),
    ]
