# Generated by Django 2.2.3 on 2019-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_name', models.CharField(max_length=300, verbose_name='白名单')),
            ],
            options={
                'verbose_name': '白名单',
                'verbose_name_plural': '白名单',
            },
        ),
        migrations.DeleteModel(
            name='UploadHost',
        ),
    ]
