# Generated by Django 2.2.3 on 2019-10-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20191025_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitename',
            name='host_ip',
            field=models.CharField(blank=True, max_length=300, verbose_name='公用电脑ip地址'),
        ),
        migrations.AlterField(
            model_name='whitename',
            name='white_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='白名单'),
        ),
    ]
