# Generated by Django 2.2.3 on 2019-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20191104_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='is_approve',
            field=models.CharField(blank=True, choices=[('1', '终审'), ('0', '')], default='0', max_length=1, verbose_name='终审'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_check',
            field=models.CharField(blank=True, choices=[('1', '初审'), ('0', '')], default='0', max_length=1, verbose_name='初审'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_confirm',
            field=models.CharField(blank=True, choices=[('1', '二审'), ('0', '')], default='0', max_length=1, verbose_name='二审'),
        ),
    ]
