# Generated by Django 2.2.3 on 2019-11-05 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20191105_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=18, unique=True, verbose_name='文件编号')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名称')),
                ('filepath', models.CharField(max_length=200, verbose_name='文件路径')),
                ('owner', models.CharField(max_length=30, verbose_name='文件所属用户')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('first_check', models.CharField(choices=[('0', '未审批'), ('1', '已审批')], default='0', max_length=1, verbose_name='初审')),
                ('second_check', models.CharField(choices=[('0', '未审批'), ('1', '已审批')], default='0', max_length=1, verbose_name='二审')),
                ('isapprove', models.CharField(choices=[('0', '未通过'), ('1', '已通过'), ('2', '已驳回')], default='0', max_length=1, verbose_name='终审')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.AlterModelOptions(
            name='publicip',
            options={'verbose_name': '公用电脑ip地址', 'verbose_name_plural': '公用电脑ip地址'},
        ),
        migrations.RemoveField(
            model_name='approvelog',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='approvelog',
            name='is_approve',
        ),
        migrations.AddField(
            model_name='approvelog',
            name='isapprove',
            field=models.CharField(choices=[('1', '已通过'), ('2', '已驳回')], default=1, max_length=1, verbose_name='终审'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvelog',
            name='fileid',
            field=models.CharField(max_length=18, verbose_name='文件编号'),
        ),
        migrations.AlterField(
            model_name='approvelog',
            name='owner',
            field=models.CharField(max_length=30, verbose_name='文件所属用户'),
        ),
        migrations.AlterField(
            model_name='publicip',
            name='host_ip',
            field=models.CharField(blank=True, max_length=300, verbose_name='公用电脑ip地址'),
        ),
    ]
