# Generated by Django 2.2.3 on 2019-11-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20191105_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvelog',
            old_name='fileid',
            new_name='fileno',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='fileid',
            new_name='fileno',
        ),
    ]
