# Generated by Django 2.2.3 on 2019-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20191106_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileno',
            field=models.CharField(max_length=18, verbose_name='文件编号'),
        ),
    ]
